### ISSUE TITLE
Kết quả thực hiện đồ án

### ISSUE THREAD

**Issue by XQuyTran** [XQuyTran/DataScience_Project_HCMUS#2]
**Những công việc nhóm đã hoàn thành:**
1. Thu thập dữ liệu.
2. Khám phá dữ liệu
3. Đưa ra câu hỏi cần trả lời
4. Xây dựng pipeline tiền xử lý và mô hình hóa dữ liệu.

**Những công việc đang thực hiện:**
1. Thử nghiệm mô hình với các siêu tham số.
2. Áp dụng mô hình trên tập kiểm tra

Nếu các bạn thấy có gì đó không ổn hay cần chỉnh sửa trong những phần nhóm đã và đang làm thì các bạn có thể bình luận ở đây. Rất cảm ơn về những góp ý của các bạn.

**Comment by kim-ali** [comment]
Các công việc bạn đã hoàn thành rât tốt, trình bày rất rõ ràng và chi tiết.
Thu thập dữ liệu: 
- Nguồn dữ liệu đủ lớn.
- Khai thác đủ tiềm năng nguồn dữ liệu.

Các phần còn lại cũng rất tốt.
Câu hỏi nhóm bạn đưa ra có tính thực tiễn và hữu ích.

Mình không có góp ý gì thêm.
